name: beathub
description: "Music service"

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter
  audioplayers: ^6.1.0
  palette_generator: ^0.3.3+5
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  icons_launcher: ^3.0.0
  flutter_lints: ^5.0.0

icons_launcher:
  image_path: "assets/icon/icon.png"
  platforms:
    android:
      enable: true
    ios:
      enable: true

flutter:
  uses-material-design: true
  assets:
     - assets/songs.json
     - assets/icon/icon.png
     - assets/images/
     - assets/songs/
